/**
 * FIT – Customer Receipt Generator
 *
 * Receipt layout follows the AS Bros / MC & SONS FISH COMPANY format:
 * • Company name + address in a bordered header box (centred)
 * • Customer Name, Bill No, Bill Date on the left (no ID field)
 * • Full-width box table (no right logistics column):
 *   Previous Balance Box — balances before today's dispatch
 *   Today's Fish Box — currentQuantity sent today
 *   Total Box — Today's Fish Box + Previous Balance Box
 *   Empty Box — left blank
 *   Total Balance Box — same as Total Box
 * • Footer notes below table:
 *   NOTE : AS & Bros Box-{n}
 *   WITHOUT BOX
 *   {SOURCE} - {qty}  (one line per external source, with hyphen separator)
 * • Contact line + "For " right-aligned
 * • Solid border footer: "Developed by: {Company}" left, "Time: {time}" right
 *
 * ── WHATSAPP SHARING ──────────────────────────────────────────────────────────
 * Desktop → fitshare:// Windows protocol handler (triggers PowerShell automation)
 * Mobile  → wa.me deep-link (opens WhatsApp app directly)
 *
 * ── CR FIX: fitshare:// PROTOCOL URL ─────────────────────────────────────────
 * The fitshare:// URL now carries phone and pdfFilename parameters so the
 * Windows PowerShell script can locate the downloaded PDF and attach it
 * to the correct WhatsApp contact — producing the SAME PDF format as the
 * "Download PDF" button.
 */

import type { BoxEntry, Customer } from '../db/database';
import { SettingsDB, CustomerDB } from '../db/database';
import { format } from 'date-fns';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface WhatsAppPayload {
  phone: string;
  webUrl: string;       // WhatsApp Web URL with pre-filled text (fallback only)
  waMe: string;         // wa.me deep link (mobile fallback)
  messageText: string;  // Plain-text summary for text-only sharing
  pdfFilename: string;  // e.g. "Receipt_BILL-042_20250715.pdf"
  altPhone?: string;    // Alternate phone number (if available)

  /**
   * ★ CR FIX — NEW FIELD ★
   * The custom Windows protocol URL that triggers the PowerShell automation.
   * Format: fitshare://send?phone=<encoded_phone>&file=<encoded_filename>
   *
   * When the browser navigates to this URL, Windows launches the registered
   * PowerShell handler (FITShareFinal.ps1 / ShareOnWhatsApp.ps1), which:
   *   1. Reads the phone number to find the right WhatsApp contact
   *   2. Reads the pdfFilename to locate the downloaded PDF in ~/Downloads
   *   3. Moves the PDF to ~/Downloads/FIT Reports
   *   4. Copies the file to the Windows clipboard (FileDropList)
   *   5. Focuses WhatsApp Web, searches for the contact, pastes the PDF, sends
   *
   * This ensures the receipt shared via WhatsApp is the EXACT SAME PDF as
   * the one generated by the "Download PDF" button.
   */
  fitshareUrl: string;
}

// ─── Device detection ─────────────────────────────────────────────────────────

export function isMobileDevice(): boolean {
  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
    navigator.userAgent,
  );
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** HTML-escape helper (used in receipt rendering) */
export function esc(s: string | null | undefined): string {
  if (!s) return '';
  return s
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/** Entry type label mapping */
export function entryTypeLabel(type: string): string {
  const map: Record<string, string> = {
    dispatch: 'BOX DISPATCH',
    return: 'BOX RETURN',
    opening_balance: 'STOCK POSITION',
    balance_forward: 'BALANCE FORWARD',
    external_source: 'FISH VARIETY',
  };
  return map[type] ?? type.replace(/_/g, ' ').toUpperCase();
}

/** Suggested PDF filename for a given entry */
export function receiptFilename(entry: BoxEntry): string {
  const safe = (entry.billNumber || entry.id).replace(/[^a-zA-Z0-9_-]/g, '_');
  return `Receipt_${safe}_${entry.entryDate.replace(/-/g, '')}.pdf`;
}

// ─── JSPDF RECEIPT — AS BROS FORMAT ──────────────────────────────────────────

export async function downloadReceiptAsPDF(
  entry: BoxEntry,
  customer: Customer,
  action: 'download' | 'open' | 'print' | 'base64' = 'download'
): Promise<string | void> {
  const settings = await SettingsDB.get();
  
  // A4 size: 210mm x 297mm
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Render the receipt twice on the same A4 page
  // First receipt at the top
  await renderReceiptContent(doc, 10, entry, customer, settings);

  // Separation line/gap
  doc.setDrawColor(200, 200, 200);
  doc.setLineDashPattern([2, 2], 0);
  doc.line(0, 148.5, 210, 148.5); // Middle of A4
  doc.setLineDashPattern([], 0);

  // Second receipt at the bottom
  await renderReceiptContent(doc, 158.5, entry, customer, settings);

  // ─── Output Actions ────────────────────────────────────────────────────────
  try {
    if (action === 'print') {
      const blob = doc.output('blob');
      const url = URL.createObjectURL(blob);
      const iframe = document.createElement('iframe');
      iframe.style.display = 'none';
      iframe.src = url;
      document.body.appendChild(iframe);
      
      iframe.onload = () => {
        setTimeout(() => {
          iframe.contentWindow?.focus();
          iframe.contentWindow?.print();
          // Cleanup after printing is triggered
          setTimeout(() => {
            document.body.removeChild(iframe);
            URL.revokeObjectURL(url);
          }, 1000);
        }, 300);
      };
      return;
    }

    if (action === 'base64') {
      return doc.output('datauristring');
    }

    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);

    if (action === 'open') {
      window.open(url, '_blank');
      return;
    }

    const a = document.createElement('a');
    a.href = url;
    a.download = receiptFilename(entry);
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      if (document.body.contains(a)) document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 2500);
  } catch (err) {
    console.error('PDF Generation failed:', err);
  }
}

async function renderReceiptContent(doc: jsPDF, startY: number, entry: BoxEntry, customer: Customer, settings: any) {
  const companyName = settings.companyName || 'MC & SONS FISH COMPANY';
  const companyAddress = settings.companyAddress || '';
  const traderName = settings.traderName || companyName;

  const billDate = format(new Date(entry.entryDate), 'dd-MM-yyyy');
  const printedAt = format(new Date(), 'hh:mm:ss a');

  // ── Box calculations ──────────────────────────────────────────────────────
  const history = await CustomerDB.getHistorySummary(customer.id, entry.billNumber);
  const previousBalanceBox = history.cumulativeBalance;
  const todayFishBox = entry.currentQuantity; 
  const totalBox = previousBalanceBox + todayFishBox;
  const totalBalanceBox = Math.max(0, totalBox - entry.boxesReturned);

  // ── External sources for footer notes ─────────────────────────────────────
  const externalSources: Array<{ name: string; qty: number }> = [];
  if (entry.openingStockSources && entry.openingStockSources.length > 0) {
    for (const src of entry.openingStockSources) {
      externalSources.push({ name: src.sourceName, qty: src.quantity });
    }
  } else if (entry.isExternalSource && entry.sourceName) {
    externalSources.push({ name: entry.sourceName, qty: entry.externalBoxCount ?? 0 });
  }

  const ownQty = entry.companyOwnQuantity ?? entry.currentQuantity;

  const PW = 210;
  const ML = 14;
  const MR = 14;
  const CW = PW - ML - MR;
  let y = startY;

  // ─── HEADER — bordered company box ───────────────────────────────────────
  const addrLines = companyAddress
    ? doc.setFontSize(8).splitTextToSize(companyAddress, CW - 60) as string[]
    : [];
  const headerH = Math.max(22, 14 + (addrLines.length * 4));

  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.8);
  doc.rect(ML, y, CW, headerH);

  // Company name — centred
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(companyName, PW / 2, y + 7, { align: 'center' });

  // Address lines
  if (addrLines.length > 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    addrLines.forEach((line: string, i: number) => {
      doc.text(line, PW / 2, y + 12 + i * 4, { align: 'center' });
    });
  }

  // Header Mobile Numbers
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  // Phone 1 (Left)
  if (settings.companyPhone) {
    doc.text(`Ph: ${settings.companyPhone}`, ML + 4, y + headerH - 4);
  }
  // Phone 2 & 3 (Right Stacked)
  if (settings.companyPhone2 || settings.companyPhone3) {
    let phY = y + headerH - 8;
    if (settings.companyPhone2) {
      doc.text(`Ph: ${settings.companyPhone2}`, PW - MR - 4, phY, { align: 'right' });
      phY += 4;
    }
    if (settings.companyPhone3) {
      doc.text(`Ph: ${settings.companyPhone3}`, PW - MR - 4, phY, { align: 'right' });
    }
  }

  y += headerH + 5;

  // ─── BILL INFO — Name/Contact (Left) | Bill No/Date (Right) ───────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(0, 0, 0);
  
  // Left: Customer info
  doc.text(`Name : ${customer.customerName || '—'}`, ML, y);
  doc.setFont('helvetica', 'normal');
  doc.text(`Contact: ${customer.mobile || '—'}`, ML, y + 6);

  // Right: Bill info
  doc.setFont('helvetica', 'bold');
  doc.text(`Bill No : ${entry.billNumber || '—'}`, PW - MR, y, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.text(`Bill Date : ${billDate}`, PW - MR, y + 6, { align: 'right' });

  y += 12;

  // ─── MAIN TABLE ───────────────────────────────────────────────────────────
  const returnedBoxesLabel = entry.boxesReturned > 0 && externalSources.length > 0 && entry.entryType === 'return'
    ? `Boxes Returned\n(${externalSources.map((s) => `${s.name}: ${s.qty}`).join(', ')})`
    : 'Boxes Returned';

  const tableRows: [string, string][] = [
    ['Previous Balance Box', String(previousBalanceBox)],
    ["Today's Fish Box", String(todayFishBox)],
    ['Total Box', String(totalBox)],
    [returnedBoxesLabel, entry.boxesReturned > 0 ? String(entry.boxesReturned) : ''], 
    ['Total Balance Box', String(totalBalanceBox)],
  ];

  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: MR },
    head: [],
    body: tableRows,
    theme: 'grid',
    styles: {
      fontSize: 9,
      cellPadding: { top: 2.5, bottom: 2.5, left: 4, right: 4 },
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.3,
      font: 'helvetica',
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 120 },
      1: { halign: 'center', fontStyle: 'bold', cellWidth: CW - 120 },
    },
  });
  y = (doc as any).lastAutoTable.finalY + 4;

  // ─── NOTES ────────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const noteText = `NOTE : AS & Bros Box-${ownQty}`;
  if (entry.entryType === 'dispatch' && externalSources.length > 0) {
    const varietyBracket = `(${externalSources.map((s) => `${s.name}: ${s.qty}`).join(', ')})`;
    doc.text(noteText, ML, y);
    doc.text(varietyBracket, ML, y + 4);
    y += 9.5;
  } else {
    doc.text(noteText, ML, y);
    y += 6;
  }

  // ─── FOOTER ───────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.text(`For ${traderName}`, PW - MR, y, { align: 'right' });

  const footerY = startY + 128; // Position relative to receipt start
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.4);
  doc.line(ML, footerY, PW - MR, footerY);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(60, 60, 60);
  doc.text(`Developed by: ${companyName}`, ML, footerY + 4);
  doc.text(`Time: ${printedAt}`, PW - MR, footerY + 4, { align: 'right' });
}

// ─── IFRAME PRINT FALLBACK (kept for backward compatibility) ──────────────────

export async function downloadCustomerReceipt(
  entry: BoxEntry,
  customer: Customer,
): Promise<void> {
  await downloadReceiptAsPDF(entry, customer);
}

// ─── WHATSAPP PAYLOAD BUILDER ─────────────────────────────────────────────────

export async function buildWhatsAppPayload(
  entry: BoxEntry,
  customer: Customer,
  overridePhone?: string,
): Promise<WhatsAppPayload> {
  const billDate = format(new Date(entry.entryDate), 'dd-MM-yyyy');

  // Dynamic history for payload (matching Dispatch UI logic)
  const history = await CustomerDB.getHistorySummary(customer.id, entry.billNumber);
  const previousBalanceBox = history.cumulativeBalance;
  const todayFishBox = entry.currentQuantity;
  const totalBox = previousBalanceBox + todayFishBox;
  const totalBalanceBox = Math.max(0, totalBox - entry.boxesReturned);

  const ownQty = entry.companyOwnQuantity ?? entry.currentQuantity;

  const externalSources: Array<{ name: string; qty: number }> = [];
  if (entry.openingStockSources && entry.openingStockSources.length > 0) {
    for (const src of entry.openingStockSources)
      externalSources.push({ name: src.sourceName, qty: src.quantity });
  } else if (entry.isExternalSource && entry.sourceName) {
    externalSources.push({ name: entry.sourceName, qty: entry.externalBoxCount ?? 0 });
  }

  const noteLines = [
    `AS & Bros Box-${ownQty}`,
  ];
  if (entry.entryType === 'dispatch' && externalSources.length > 0) {
    noteLines.push(`(${externalSources.map((s) => `${s.name}: ${s.qty}`).join(', ')})`);
  }

  const lines = [
    `🐟 *FIT – Fish Inventory Tracking*`,
    ``,
    `🧾 *Bill No:* ${entry.billNumber} 📅 *Date:* ${billDate}`,
    `👤 *Name:* ${customer.customerName}`,
    `🏪 *Shop:* ${customer.shopName || '—'}`,
    ``,
    `━━━━━━━━━━━━━━━━━━━━━━━`,
    `📦 Previous Balance Box : *${previousBalanceBox}*`,
    `📤 Today's Fish Box     : *${todayFishBox}*`,
    `📊 Total Box            : *${totalBox}*`,
    `↩️ Boxes Returned       : *${entry.boxesReturned}*` + (entry.boxesReturned > 0 && externalSources.length > 0 && entry.entryType === 'return' ? `\n   (${externalSources.map((s) => `${s.name}: ${s.qty}`).join(', ')})` : ''),
    `⚖️ Total Balance Box    : *${totalBalanceBox}*`,
    `━━━━━━━━━━━━━━━━━━━━━━━`,
    ``,
    `NOTE : ${noteLines.join('\n ')}`,
    ``,
    totalBalanceBox === 0
      ? `✅ All boxes returned. Thank you!`
      : `⚠️ *${totalBalanceBox} box${totalBalanceBox !== 1 ? 'es' : ''} pending return.*`,
    ``,
    `_Thank you for your business!_`,
  ];

  const messageText = lines.join('\n');

  const rawPhone = (overridePhone || customer.mobile || '').replace(/\D/g, '');
  const e164Digits = rawPhone.length >= 11 ? rawPhone : rawPhone ? `91${rawPhone}` : '';
  const phonePlus = e164Digits ? `+${e164Digits}` : '';

  const rawAlt = (customer.alternateMobile || '').replace(/\D/g, '');
  const e164Alt = rawAlt.length >= 11 ? rawAlt : rawAlt ? `91${rawAlt}` : '';
  const altPhonePlus = e164Alt ? `+${e164Alt}` : '';

  const encoded = encodeURIComponent(messageText);
  const waMe = e164Digits
    ? `https://wa.me/${e164Digits}?text=${encoded}`
    : `https://wa.me/?text=${encoded}`;
  const webUrl = e164Digits
    ? `https://web.whatsapp.com/send?phone=${e164Digits}&text=${encoded}`
    : `https://web.whatsapp.com/send?text=${encoded}`;

  // ──────────────────────────────────────────────────────────────────────────
  // ★ CR FIX — Generate the fitshare:// protocol URL ★
  //
  // The fitshare:// URL carries both the phone number and the PDF filename
  // so the Windows PowerShell handler can:
  //   1. Locate the downloaded PDF in ~/Downloads/<pdfFilename>
  //   2. Find the correct WhatsApp contact by phone number
  //   3. Attach and send the exact same PDF as "Download PDF" produces
  //
  // URL Format: fitshare://send?phone=<encoded_phone>&file=<encoded_filename>
  // ──────────────────────────────────────────────────────────────────────────
  const pdfFilename = receiptFilename(entry);
  const fitshareUrl = `fitshare://send?phone=${encodeURIComponent(phonePlus)}&file=${encodeURIComponent(pdfFilename)}`;

  return {
    phone: phonePlus,
    webUrl,
    waMe,
    messageText,
    pdfFilename,
    fitshareUrl, // ★ NEW FIELD
    altPhone: altPhonePlus,
  };
}

// ─── SHARING FUNCTIONS (all kept for backward compatibility) ──────────────────

export function openWhatsAppWeb(payload: WhatsAppPayload): void {
  window.open(payload.waMe, '_blank');
}

/**
 * ★ CR FIX — triggerWhatsAppAutomation ★
 *
 * BEFORE (buggy):
 *   - Called downloadReceiptAsPDF() ✓
 *   - Then navigated to payload.webUrl (WhatsApp Web URL with TEXT only) ✗
 *   - The PDF was never shared — only a text message appeared
 *
 * AFTER (fixed):
 *   - Calls downloadReceiptAsPDF() ✓
 *   - Then navigates to payload.fitshareUrl (fitshare://send?phone=...&file=...) ✓
 *   - Windows resolves fitshare:// → PowerShell script
 *   - PowerShell finds the downloaded PDF, copies it to clipboard,
 *     focuses WhatsApp Web, finds the contact by phone, pastes & sends
 *   - Result: The exact SAME PDF as "Download PDF" is shared via WhatsApp
 */
export async function triggerWhatsAppAutomation(
  payload: WhatsAppPayload,
  entry: BoxEntry,
  customer: Customer,
): Promise<void> {
  // Step 1: Download the PDF to the user's Downloads folder
  await downloadReceiptAsPDF(entry, customer);

  const url = payload.fitshareUrl;

  setTimeout(() => {
    window.location.href = url;
  }, 800);
}

export async function shareMobile(
  entry: BoxEntry,
  customer: Customer,
  overridePhone?: string,
): Promise<void> {
  await downloadReceiptAsPDF(entry, customer);
  const payload = await buildWhatsAppPayload(entry, customer, overridePhone);
  setTimeout(() => {
    window.location.href = payload.waMe;
  }, 600);
}

export async function shareReceiptViaWhatsApp(
  entry: BoxEntry,
  customer: Customer,
  overridePhone?: string,
): Promise<void> {
  if (isMobileDevice()) {
    await shareMobile(entry, customer, overridePhone);
  } else {
    const payload = await buildWhatsAppPayload(entry, customer, overridePhone);
    await triggerWhatsAppAutomation(payload, entry, customer);
  }
}
