// FIT – PDF Bill Generator v2.0
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { BoxEntry, Customer } from '../db/database';
import { SettingsDB } from '../db/database';
import { format } from 'date-fns';

export async function generateBillPDF(entry: BoxEntry, customer: Customer): Promise<jsPDF> {
  const settings = await SettingsDB.get();
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a5' });

  // ─── Header ───────────────────────────────────────────────────────────────
  doc.setFillColor(13, 71, 161);
  doc.rect(0, 0, 148, 24, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(settings.companyName || 'FIT – Fish Inventory Tracking', 74, 10, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  if (settings.companyAddress) {
    doc.text(settings.companyAddress, 74, 16, { align: 'center' });
  }
  if (settings.companyPhone) {
    doc.text(`Ph: ${settings.companyPhone}${settings.gstNumber ? '  |  GST: ' + settings.gstNumber : ''}`, 74, 21, { align: 'center' });
  }

  // ─── Bill title bar ────────────────────────────────────────────────────────
  doc.setFillColor(230, 239, 255);
  doc.rect(0, 24, 148, 8, 'F');
  doc.setTextColor(13, 71, 161);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('BOX DISPATCH BILL', 74, 30, { align: 'center' });

  // ─── Bill meta ────────────────────────────────────────────────────────────
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(8.5);
  let y = 38;

  const metaRows = [
    ['Bill No', entry.billNumber, 'Date', format(new Date(entry.entryDate), 'dd MMM yyyy')],
    ['Driver', entry.driverName || '—', 'Vehicle', entry.vehicleNumber || '—'],
  ];
  metaRows.forEach(([l1, v1, l2, v2]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${l1}:`, 10, y);
    doc.setFont('helvetica', 'normal');
    doc.text(v1, 30, y);
    doc.setFont('helvetica', 'bold');
    doc.text(`${l2}:`, 80, y);
    doc.setFont('helvetica', 'normal');
    doc.text(v2, 100, y);
    y += 6;
  });

  // ─── Customer block ───────────────────────────────────────────────────────
  y += 2;
  doc.setFillColor(232, 240, 254);
  doc.rect(8, y - 3, 132, 22, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.text('CUSTOMER DETAILS', 10, y + 1);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`Name: ${customer.customerName}`, 10, y);
  doc.text(`Shop: ${customer.shopName}`, 75, y);
  y += 5;
  doc.text(`Mobile: ${customer.mobile}`, 10, y);
  if (customer.email) doc.text(`Email: ${customer.email}`, 75, y);
  y += 5;
  if (customer.address) {
    doc.text(`Address: ${customer.address}`, 10, y);
  }

  // ─── Box details table ────────────────────────────────────────────────────
  y += 10;
  autoTable(doc, {
    startY: y,
    head: [['Description', 'Value']],
    body: [
      ['Entry Type', entry.entryType.replace(/_/g, ' ').toUpperCase()],
      ['Total Boxes Sent (Cumulative)', String(entry.totalBoxesSent)],
      ['Current Qty Dispatched — Own Inventory', String(entry.currentQuantity)],
      ...(entry.isExternalSource
        ? [
            ['External Source', entry.sourceName || ''],
            ['External Box Count', String(entry.externalBoxCount ?? 0)],
          ]
        : []),
      ['Total Boxes Sent (incl. External)', String(entry.totalBoxesSent + entry.currentQuantity + (entry.isExternalSource ? (entry.externalBoxCount ?? 0) : 0))],
      ['Boxes Returned', String(entry.boxesReturned)],
      ['Balance Boxes', String(entry.balanceBoxes)],
      ['Description / Notes', entry.description || '—'],
    ],
    headStyles: { fillColor: [13, 71, 161], textColor: 255, fontSize: 8.5, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [245, 248, 255] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 65, fillColor: [240, 245, 255] },
      1: { cellWidth: 65 },
    },
    margin: { left: 8, right: 8 },
  });

  // ─── Signature area ───────────────────────────────────────────────────────
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(7.5);
  doc.setTextColor(80, 80, 80);
  doc.text('Receiver Signature: ________________________', 10, finalY);
  doc.text('Authorised by: ________________________', 10, finalY + 8);

  // ─── Footer ───────────────────────────────────────────────────────────────
  doc.setDrawColor(13, 71, 161);
  doc.setLineWidth(0.3);
  doc.line(8, finalY + 16, 140, finalY + 16);
  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  doc.text(
    `Generated by FIT – Fish Inventory Tracking System  |  ${format(new Date(), 'dd MMM yyyy HH:mm')}`,
    74,
    finalY + 20,
    { align: 'center' }
  );

  return doc;
}

export function shareBillViaWhatsApp(entry: BoxEntry, customer: Customer): void {
  const msg = [
    `🐟 *FIT – Fish Inventory Tracking*`,
    ``,
    `📋 *Bill No:* ${entry.billNumber}`,
    `📅 *Date:* ${format(new Date(entry.entryDate), 'dd MMM yyyy')}`,
    ``,
    `👤 *Customer:* ${customer.customerName}`,
    `🏪 *Shop:* ${customer.shopName}`,
    ``,
    `📦 *Total Boxes Sent:* ${entry.totalBoxesSent}`,
    `📥 *Boxes Returned:* ${entry.boxesReturned}`,
    `⚖️ *Balance Boxes:* ${entry.balanceBoxes}`,
    ``,
    entry.driverName ? `🚛 *Driver:* ${entry.driverName}` : '',
    entry.vehicleNumber ? `🚗 *Vehicle:* ${entry.vehicleNumber}` : '',
    ``,
    entry.description ? `📝 *Note:* ${entry.description}` : '',
    ``,
    `_Thank you for your business!_`,
  ]
    .filter((line) => line !== undefined)
    .join('\n');

  const phone = customer.mobile.replace(/\D/g, '');
  const encoded = encodeURIComponent(msg);
  const url = phone
    ? `https://wa.me/91${phone}?text=${encoded}`
    : `https://wa.me/?text=${encoded}`;
  window.open(url, '_blank');
}
